### ISSUE TITLE
Add compatability to HTTP headers

### ISSUE THREAD

**Issue by mykhailohoy** [brockfanning/jekyll-get-json#3]
If api is private, it is impossible to use the plugin. This feature would be awesome.

**Comment by brockfanning** [comment]
@mykhailohoy Can you give an example of how you would like to control the HTTP headers? This is what came to mind for me, in the _config.yml file:

```
jekyll_get_json:
    http_headers:
        MY-HEADER: my value
        MY-OTHER-HEADER: my other value
```

However I'm wondering if the use-case was to add passwords/secrets for authentication purposes. If so, that wouldn't work if the code were public.
